name: 'Auto Release Notes'
description: 'Github action to have auto release notes published to Microsoft Teams'
inputs:
  github-token:
    description: 'Github Token to be used for action'
    required: true
  version:
    description: 'Version of code being deployed'
    required: true
  service-name:
    description: 'Name of service being deployed.'
    required: true
  team-name:
    description: 'Name of team that owns application.'
    required: true
  ms-teams-webhook-url:
    description: 'Microsoft Teams webhook to send request to'
    required: true
runs:
  using: "composite"
  steps:

    - name: Create MS Teams JSON File
      shell: bash
      run: cat ${{ github.action_path }}/ms-teams-card.json >> ms-teams-card.json

    - name: Get Current Date
      shell: bash
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Find and Replace Service Name
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Name of Service>"
        replace: ${{ inputs.service-name }}

    - name: Find and Replace Team Name
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Team Name>"
        replace: ${{ inputs.team-name }}

    - name: Find and Replace Version
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Version>"
        replace: ${{ inputs.version }}

    - name: Find and Replace Date
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Date Released>"
        replace: ${{ steps.date.outputs.date }}

    - name: Find and Replace Github URL
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Repository URL>"
        replace: ${{ github.server_url }}/${{ github.repository }}

    - name: Read ms-teams-card.json
      id: read-json
      uses: juliangruber/read-file-action@v1
      with:
        path: ./ms-teams-card.json

    - name: Update Changelog
      if: ${{ success() }}
      uses: BobAnkh/auto-generate-changelog@v1.2.2
      with:
        ACCESS_TOKEN: ${{ inputs.github-token }}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'chore(bot): update files for Release ${{ inputs.version }}.'
        TYPE: |
          feat:Feature,
          fix:Bug Fixes,
          style:Styling,
          refactor:Refactor,
          perf:Performance Improvements,
          test:Testing Changes,
          docs:Documentation,
          chore:Miscellaneous

    - name: Post to MS Teams Channel
      if: ${{ success() }}
      uses: fjogeleit/http-request-action@v1.11.0
      with:
        url: ${{ inputs.ms-teams-webhook-url}}
        method: 'POST'
        data: ${{ steps.read-json.outputs.content }}
